@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePatientList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-down-> "1" AppointmentList
AddressBook *-down-> "1" AppointmentViewList
UniqueTagList -[hidden]down- UniquePatientList
UniqueTagList -[hidden]down- UniquePatientList

UniqueTagList -right-> "*" Tag
UniquePatientList -right-> Patient
AppointmentList -down-> Appointment
AppointmentViewList -down-> AppointmentView

Patient -up-> "*" Tag

Patient *--> Name
Patient *--> Nric
Patient *--> DateOfBirth
Patient *--> Phone
Patient *--> Email
Patient *--> Address

Appointment *--> Nric
Appointment *--> Date
Appointment *--> TimePeriod
Appointment *--> AppointmentType
Appointment *--> Note

AppointmentView *--> Name
AppointmentView *--> Appointment

TimePeriod *--> "2" Time

@enduml
