@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes EditApptCommand;

if () then ([Patient with NRIC found])
    if () then ([Appointment with NRIC, Date, StartTime found])
        if () then ([Valid new values for appointment])
            if () then ([New appointment does not overlap with existing])
                if () then ([Appointment date not before DOB])
                    :Update Appointment in
                    AppointmentList in AddressBook;
                else ([Appointment date before DOB])
                    :CommandException;
                endif
            else ([New appointment overlaps with existing])
                :CommandException;
            endif
        else ([Invalid new values for appointment])
            :CommandException;
        endif
    else ([Appointment not found])
        : CommandException;
    endif
else ([NRIC not found])
    : CommandException;
endif
stop
@enduml
