@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start

:User executes command;
if () then ([Invalid arguments])
  :Alert user of error;
    else ([Valid arguments])
      while () is ([More appointments to filter])
        :Process next appointment;
        if () then ([Pass check])
          :Add appointment to list;
        else ([No])
        endif
        endwhile ([All checked])
      :Return filtered list of appointments;
      :Display list;
      :User gets feedback;
    endif
    stop
@enduml
